before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  # Required for inter service communication
  FF_NETWORK_PER_BUILD: "TRUE"
  # PostgreSQL environment
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "odoo"
  POSTGRES_PASSWORD: "odoo"

cache:
  paths:
    - .gradle
    - .m2

test-odoo14:
  image: openjdk:11
  stage: test
  services:
    - name: odoo:14
      alias: odoo
      entrypoint: [ "/entrypoint.sh", "odoo", "-d", "db1", "-i", "hr", "--db_host=db", "--db_user=odoo", "--db_password=odoo" ]

    - name: postgres:12.2
      alias: db

  script:
    - ./gradlew test

test-odoo10:
  image: openjdk:11
  stage: test
  services:
    - name: odoo:10
      alias: odoo
      entrypoint: [ "/entrypoint.sh", "odoo", "-d", "db1", "-i", "hr", "--db_host=db", "--db_user=odoo", "--db_password=odoo" ]

    - name: postgres:12.2
      alias: db

  script:
    - ./gradlew test

build:
  image: openjdk:11
  stage: build

  script:
    - ./gradlew clean jar

  artifacts:
    paths:
      - build/libs/*.jar

