version: '3.9'

services:

  odoo:
    image: odoo:14
    depends_on:
      - db-odoo
    ports:
      - 10082:8069
    environment:
      - HOST=db-odoo
      - USER=odoo
      - PASSWORD=odoo

  db-odoo:
    image: postgres:12.2
    ports:
      - 15434:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    # if you need to debug odoo SQL statements: use this command to log all SQL statements in postgres
    #command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - pg_odoo_data:/var/lib/postgresql/data

volumes:
  pg_odoo_data:
    driver: local

networks:
  default:
    name: odoo-connector-test-network